[build]
  publish = "_site"
  command = "if [[ ! $BRANCH =~ ^renovate ]] && [[ ! $HEAD =~ ^renovate ]]; then npm run build:netlify && JEKYLL_ENV=production jekyll build --verbose; else mkdir _site; fi"
